Resources:
  NotesFunction:
    Type: AWS::Serverless::Function
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: .
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      Timeout: 10
      MemorySize: 128
      Events:
        NotesApi:
          Type: Api
          Properties:
            Path: /notes
            Method: ANY
